---
#- hosts: all
- hosts: switches
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - common
#    - interfaces
#    - loopbacks
    - Test
  handlers:
    - include: handlers/main.yml
